<a href="https://colab.research.google.com/github/jacobwolter2000/Math242/blob/main/Gram_Schmidt_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [15]:
# Create a Vector:
r1 = np.array([3,0,3,0])
r1

array([3, 0, 3, 0])

In [9]:
# Vector Arithmetic: 
3*r1

array([9, 0, 9, 0])

In [11]:
# Vector Dot Product:
r1.dot(r1)

18

In [13]:
# Square Roots:
np.sqrt(9)

3.0

In [16]:
# Magnitude of vector: 
np.sqrt(r1.dot(r1))

4.242640687119285

#Gram-Schmidt Orthonormalization Process

Well use the Gram-Schmidt process to find orthogonal vectors in $R^4$

## Our "Random" Vectors:

In [17]:
r1= np.array([3,0,3,0])
r2= np.array([3,2,3,3])
r3= np.array([-7,-4,-5,-6])
r4= np.array([-7,-3,-11,2])

## Process $r_1$

In [24]:
# Choose the vector and subtract off the "Nice" orthogonal pieces
t1=r1
#t1
#Find the size of t1
m= np.sqrt(t1.dot(t1))

# Create the nice orthonormal vector u1
u1= (1/m)*t1
u1



array([0.70710678, 0.        , 0.70710678, 0.        ])

## Process $r_2$

In [27]:
# Choose the vector and subtract off the "Nice" orthogonal pieces
t2=r2 - (u1.dot(r2))*u1
#t1
#Find the size of t1
m= np.sqrt(t2.dot(t2))
m
# Create the nice orthonormal vector u1
u2= (1/m)*t2
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

##Process $r_3$

In [28]:
# Choose the vector and subtract off the "Nice" orthogonal pieces
t3=r3 - (u1.dot(r3))*u1-(u2.dot(r3))*u2
#t1
#Find the size of t1
m= np.sqrt(t3.dot(t3))
m
# Create the nice orthonormal vector u1
u3= (1/m)*t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

## Process $r_4$

In [30]:
# Choose the vector and subtract off the "Nice" orthogonal pieces
t4=r4 - (u1.dot(r4))*u1-(u2.dot(r4))*u2-(u3.dot(r4))*u3
#t1
#Find the size of t1
m= np.sqrt(t4.dot(t4))
m
# Create the nice orthonormal vector u1
u4= (1/m)*t4
u4

array([ 0.        , -0.83205029,  0.        ,  0.5547002 ])

## Checks

In [34]:
print(u1.dot(u1))
print(u1.dot(u2))
print(u1.dot(u3))
print(u1.dot(u4))
print(u2.dot(u2))
print(u2.dot(u3))
print(u2.dot(r4))
print(u3.dot(u3))
print(u3.dot(u4))
print(u4.dot(u4))


1.0000000000000002
-1.741861189847285e-16
0.0
0.0
1.0
-6.967444759389139e-16
2.220446049250313e-15
0.9999999999999998
-8.709305949236341e-17
1.0


In [ ]:
print("r1=")
print()