<a href="https://colab.research.google.com/github/jacobwolter2000/Math242/blob/main/Take_Home_Test_1_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Initialize the preliminary code:


In [1]:
import numpy as np
from numpy import c_

ll = "loaded"

In [2]:
# create the matrix M:
M = np.matrix([[1/2, 1/2, 1/5],
               [1/4, 0, 2/5],
               [1/4, 1/2, 2/5]])
M

matrix([[0.5 , 0.5 , 0.2 ],
        [0.25, 0.  , 0.4 ],
        [0.25, 0.5 , 0.4 ]])

In [9]:
x0 = np.matrix([[100], [100], [100]])
x0

matrix([[100],
        [100],
        [100]])

In [10]:
xb=M**-1*x0
xb

matrix([[133.33333333],
        [  0.        ],
        [166.66666667]])

In [12]:
np.linalg.inv(M) * x0

matrix([[133.33333333],
        [  0.        ],
        [166.66666667]])

In [4]:
x1=M*x0
x1

matrix([[150.],
        [ 25.],
        [125.]])

In [5]:
x10min=M**2*x0
x10min

matrix([[112.5],
        [ 87.5],
        [100. ]])

In [6]:
x20min=M**4*x0
x20min

matrix([[116.4375],
        [ 74.75  ],
        [108.8125]])

In [7]:
x4hr=M**48*x0
x4hr

matrix([[117.07317073],
        [ 73.17073171],
        [109.75609756]])