<a href="https://colab.research.google.com/github/jacobwolter2000/Math242/blob/main/Take_Home_Test_1_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Initialize the preliminary code:


In [1]:
import numpy as np
from numpy import c_

ll = "loaded"

In [3]:
# create the matrix M:
M = np.matrix([[1/2, 1/2, 1/5],
               [1/4, 0, 2/5],
               [1/2, 1/2, 2/5]])
M

matrix([[0.5 , 0.5 , 0.2 ],
        [0.25, 0.  , 0.4 ],
        [0.5 , 0.5 , 0.4 ]])

In [4]:
x0 = np.matrix([[100], [200], [0]])
x0

matrix([[100],
        [200],
        [  0]])

In [5]:
x1=M*x0
x1

matrix([[150.],
        [ 25.],
        [150.]])

In [16]:
x10min=M**2*x0
x10min

matrix([[117.5],
        [ 97.5],
        [147.5]])

In [17]:
x20min=M**4*x0
x20min

matrix([[145.9875],
        [100.85  ],
        [179.2875]])

In [18]:
x4hr=M**48*x0
x4hr

matrix([[5523.38549827],
        [3765.17714861],
        [6770.21767213]])